source 'https://rubygems.org'

gem 'rake'
gem 'pry'
gem 'elasticsearch'
gem 'hashie', '~> 3'
gem 'rubyzip', '>= 1.0.0'
gem 'aws-sdk', '~> 2'
gem 'whenever', '~> 0.9.4'
group :development, :test do
  gem 'rspec'
  gem 'timecop'
end
